TheWorld/Models/IWorldRepository.cs
using System.Collections.Generic;

namespace TheWorld.Models
{
    public interface IWorldRepository
    {
        IEnumerable<Trip> GetAllTrips();
    }
}

TheWorld/Models/Stop.cs
using System;

namespace TheWorld.Models
{
    public class Stop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int Order { get; set; }
        public DateTime Arrival { get; set; }




    }
}

TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public DateTime DateCreated { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

TheWorld/Models/WorldContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;

namespace TheWorld.Models
{
    public class WorldContext : DbContext
    {
        private IConfigurationRoot _config;

        public WorldContext(Microsoft.Extensions.Configuration.IConfigurationRoot config, DbContextOptions options) : base()
        {
            _config = config;
        }

        public DbSet<Trip> Trips { get; set; }
        public DbSet<Stop> Stops { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);

            optionsBuilder.UseSqlServer(_config["ConnectionStrings:WorldContextConnection"]);


        }


    }
}

TheWorld/Models/WorldRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class WorldRepository : IWorldRepository
    {
        private WorldContext _context;

        public WorldRepository(WorldContext context)
        {
            _context = context;
        }


        public IEnumerable<Trip> GetAllTrips()
        {
            return _context.Trips.ToList();
        }
    }
}

TheWorld/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TheWorld.ViewModels
{
    public class ContactViewModel
    {

        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }

    }
}

TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheWorld.Services;
using Microsoft.Extensions.Configuration;
using TheWorld.Models;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;
        private IWorldRepository _repository;

        public AppController(IMailService mailService, IConfigurationRoot config, IWorldRepository repository)
        {
            _mailService = mailService;
            _config = config;
            _repository = repository;
        }
        public IActionResult Index()
        {
            //Go to database and get all Trips as List classes..
            var data = _repository.Trips;
            return View(data);
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ViewModels.ContactViewModel model)
        {

            if (model.Email.Contains("aol.com")) ModelState.AddModelError("Email", "We dont support AOL addresses");

            if (ModelState.IsValid)
            {
                _mailService.SendMail(_config["MailSettings:ToAddress"], model.Email, "From TheWorld", model.Message);

                ModelState.Clear();
                ViewBag.UserMessage = "Message Sent";
            }

                return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

TheWorld/Views/App/About.cshtml
@{
    ViewBag.Title = "About Page";
}
<h2>About The World</h2>

TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{ 
    ViewBag.Title = "Contact Page";
}

@section scripts {
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<h2>Contact Me</h2>
<form method="post">
    <span asp-validation-summary="ModelOnly"></span>
    @if (ViewBag.UserMessage != null)
    {
        <div>@ViewBag.UserMessage</div>

    }
    <label asp-for="Name">Name</label>
    <input asp-for="Name"/>
    <span asp-validation-for="Name"></span>
    <label asp-for="Email">Email</label>
    <input type="email" asp-for="Email" />
    <span asp-validation-for="Email"></span>
    <label asp-for="Message">Message</label>
    <textarea cols="40" rows="4" asp-for="Message"></textarea>
    <span asp-validation-for="Message"></span>
    <div>
        <input type="submit" value="SendMessage" />
    </div>
</form>

TheWorld/Views/App/Index.cshtml
@model IEnumerable<TheWorld.Models.Trip>
@{ 
    ViewBag.Title = "Home Page";
    Layout = "_Layout";

}
            <h3>Nozama</h3>
            <p>The Nozama Lite home page.</p>

            <form>
                <div>
                    <label>Date</label>
                    <input />
                </div>
                <div>
                    <label>Location</label>
                    <input />
                </div>
                <div>
                    <input type="submit" value="Add" />
                </div>

                <div>
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.DateCreated;</li>


                }

        </ul>

            </div>

            </form>

TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Nozama - @ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/site.css" />


</head>


<body>

    <div id="sidebar">
        <img src="~/img/theDude.jpg" alt="The Dude" class="headshot" />
        <span id="username">The Dude</span>
        <ul class="menu">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>

        </ul>

    </div>

    <div id="wrapper">
        <div id="main">
            <div>
                <button id="sidebarToggle">Toggle Menu</button>
            </div>


            @RenderBody()

        </div>


            <div id="footer">&copy; 2017 The Jenkins Corporation Ltd.</div>

      
    </div>


    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("scripts", false)


    <script type="text/javascript" src="~/js/site.js">

    </script>

</body>




</html>